version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-multitenant
    restart: always
    environment:
      POSTGRES_DB: clienta
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
    ports:
      - "5432:5432"
    volumes:
        - ./postgres-init:/docker-entrypoint-initdb.d
        - ./postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf
    tmpfs:
      - /var/lib/postgresql/data
    command: postgres -c hba_file=/etc/postgresql/pg_hba.conf

    networks:
      - notif-network

  notification-service:
    image: imr/notification-service:latest  # <-- Replace with your image name
    container_name: notification-service
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/clienta
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PWD}
      LOG_PATH: /logs
      SMTP_HOST:  ${SMTP_HOST}
      SMTP_PORT:  ${SMTP_PORT}
      SMTP_USERNAME:  ${SMTP_USERNAME}
      SMTP_PASSWORD:  ${SMTP_PASSWORD}
      DB_USER: ${DB_USER}
      DB_PWD: ${DB_PWD}
      DB_NAME: clienta
    ports:
      - "8080:8080"
    networks:
      - notif-network

volumes:
  postgres_data:

networks:
  notif-network:
